### ISSUE TITLE
Nodes sticking to Shelf

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#129]
If I load a dataset (in this case, SHARP2017), and drag in people, some of the nodes stick to the shelf and won't drag into the center.
Here, I pulled Sophia King into the middle of graph, and everything joined her except for English.

![screen shot 2017-11-01 at 10 42 57 am](https://user-images.githubusercontent.com/11494469/32280342-e7b07206-bef1-11e7-818b-e1b4dcee18e6.png)

**Comment by smurp** [comment]
I've not been able to make this happen anymore -- perhaps I'm unclear on which dataset/ontology combo is doing this.

**Comment by antimony27** [comment]
![image](https://user-images.githubusercontent.com/11494469/41609624-41f154c0-73b9-11e8-920d-cd991e594226.png)

Still happening. We think this is likely a data issue, but I'm leaving it here for @smurp to investigate. 

Data file: HuVizSharp2017  Onto: OwlMini (because CWRC onto not working)

**Comment by antimony27** [comment]
And one more example:
![image](https://user-images.githubusercontent.com/11494469/42822697-af7ddb02-89a9-11e8-90be-0492fb8c8670.png)
This always happens with the CWRC onto node. It won't move away from the shelf. If you drag it to make it part of the node clustered inside, it still goes back to the shelf when you release.

**Comment by smurp** [comment]
I think we should distinguish between nodes which are not connected (#99) and nodes which are stuck on the shelf -- which I am still seeing occasionally.

**Comment by smurp** [comment]
The broken sort order in #109 might be related to this stick shelf issue -- that was the case the last time I dealt with this a few years ago -- the sort order being broken **caused** the sticky shelf.

**Comment by antimony27** [comment]
Closing, hopefully this is fixed.

**Comment by smurp** [comment]
Sadly I think we're still seeing this one.  I'd even say it is a very top priority.

**Comment by antimony27** [comment]
Where did you see this @smurp ? I think we should investigate the datasets, unless its coming from the Sparql endpoint?
