### ISSUE TITLE
CWRC ontology loading issues

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#158]
From @smurp 's email:
There are three possible solutions as I understand it:
1) host (or serve) the file from GitHub because http://raw.githubusercontent.com/ is set up to permit CORS connections

2) have Jeffery configure http://sparql.cwrc.ca/ontology/ to permit CORS access to the ontologies by setting a header on delivered content which looks like this:
'Access-Control-Allow-Origin: *'
This could be made more specific so just particular domains can perform such queries, but I would recommend just using the universal wildcard "*" as in the example, since this information is not a secret.

3) Have me add proxy technology to the HuViz server so urls like:
  http://alpha.huviz.dev.nooron.com/GO_FETCH/http://sparql.cwrc.ca/ontology/cwrc.ttl
cause the HuViz server to fetch the requested document and return it to the user.  This would route around the conditions which trigger the CORS security measures.  This does have the unfortunate quality of turning the HuViz server into an open proxy -- meaning that bad actors can then trigger the server to go get verboten content while coming from the HuViz server.  This can be remedied by putting some constraints on what is proxied -- A) by extension (.ttl, .owl, .nt., .nq, etc) or B) by using a whitelist of servers which can be proxied -- I suggest A) by extension.

@SusanBrown has been in touch with Joel who will get back to us asap, though we are currently looking at solution B.

**Comment by SusanBrown** [comment]
Should be fixed. Waiting on further testing by @antimony27 or @cmiya

**Comment by antimony27** [comment]
I still can't get the CWRC onto to load. Tested with several datasets, including the new triples Joel created.

**Comment by smurp** [comment]
Using http://alpha.huviz.dev.nooron.com/ I was just now able to visualize the `CWRC Ontology` listed as being hosted over at `sparql.cwrc.ca`.  I was also able to visualize `HuVizSHARP2017` using the `CWRC Ontology`.  In the second case I know that the ontology was successfully loading because the class picker had depth to it.

**Comment by antimony27** [comment]
Yes - we've been able to get it working as well. Apologies for not writing sooner! Closing... with hope.
