### ISSUE TITLE
Clicking specific class (e.g. Organization) selects all classes

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#178]
## Expected Behaviour
We you start from a state where all nodes are Unselected, clicking an individual Class drawer should just select the one class. 

## Current Behaviour
Instead, all classes are selected (nodes in graph are also bolded, so they've definitely been selected).
<img width="415" alt="screen shot 2018-10-01 at 10 51 36 am" src="https://user-images.githubusercontent.com/13421476/46279236-d96efb80-c568-11e8-80eb-03385f2ca63f.png">

## Steps to Reproduce (for bugs)

1. Select the Ada Byron dataset (under Individuals) and the default Orlando dataset ****I've also tried this with the HuVizSharp dataset and the CWRC ontology and have the same problem**
2. (To Unselect All), click **'All'** under Sets.
3. Under Verbs, click **'Unselect.'**
4. Under Class, click **Organization** (or any other individual class).

## Your Environment
* URL: http://huviz.dev.nooron.com/

* Browser Name: Chrome

* Operating System:

* Attachements:

* CWRC user name if submitting an issue for the CWRC research space, or the Github username if using GitWriter.

**Comment by smurp** [comment]
This is fixed in beta and alpha.

http://beta.huviz.dev.nooron.com/#load+/data/byroau.nq+with+https://cwrc.ca/ontologies/OrlandoOntology-2015-11-16.ttl

Production is looking pretty unusable in this condition, perhaps we should push beta into production?

Alpha has some great stuff in it but exposes a currently incomplete SPARQL menu.

**Comment by SusanBrown** [comment]
I found beta in good shape when I was using it recently, and had some real problems with alpha when I mistakenly used it. But has anyone else used beta since it was pushed from alpha last week? I think we should have a second opinion on this from someone else who’s also used the newest version of beta.


On Oct 24, 2018, at 3:20 PM, Shawn Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


This is fixed in beta and alpha.

http://beta.huviz.dev.nooron.com/#load+/data/byroau.nq+with+https://cwrc.ca/ontologies/OrlandoOntology-2015-11-16.ttl

Production is looking pretty unusable in this condition, perhaps we should push beta into production?

Alpha has some great stuff in it but exposes a currently incomplete SPARQL menu.

**Comment by antimony27** [comment]
@cmiya Could you retest this and see if its still happening? If not, please close.
